### ISSUE TITLE
ffi.error: struct tr_tcp_config: wrong total size (cdef says 24, but C compiler says 48).

### ISSUE THREAD

**Issue by yuch5517** [rtrlib/python-binding#17]
When I was using the python-binding, I tried using RTRManager. However, the following error occurred. Could it be due to an update in the rtrlib code that this repository has not yet updated?
```
Traceback (most recent call last):
  File "rtr_receiver.py", line 41, in <module>
    main()
  File "rtr_receiver.py", line 37, in main
    start_rtr_receiver(rtr_host, rtr_port)
  File "rtr_receiver.py", line 11, in start_rtr_receiver
    manager = RTRManager(rtr_host, rtr_port,pfx_update_callback=callback)
  File "/usr/local/lib/python3.8/dist-packages/rtrlib-0.1-py3.8-linux-x86_64.egg/rtrlib/rtr_manager.py", line 138, in __init__
    self.tcp_config = ffi.new('struct tr_tcp_config *')
ffi.error: struct tr_tcp_config: wrong total size (cdef says 24, but C compiler says 48). fix it or use "...;" as the last field in the cdef for struct tr_tcp_config to make it flexible
```

**Comment by jayeshkumarbhoi** [comment]
Yes I do have same issue.

```
File "/usr/local/lib/python3.12/site-packages/rtrlib-0.1-py3.12-linux-x86_64.egg/rtrlib/rtr_manager.py", line 138, in __init__
    self.tcp_config = ffi.new('struct tr_tcp_config *')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ffi.error: struct tr_tcp_config: wrong total size (cdef says 24, but C compiler says 48). fix it or use "...;" as the last field in the cdef for struct tr_tcp_config to make it flexible
```

I have found it was works with` cffi==1.15.1` but now it pulling latest cffi which is `cffi==1.16.0` and with this version above error started to appear.

**Comment by jayeshkumarbhoi** [comment]
Anyone have idea how to resolve this issue?

**Comment by mroethke** [comment]
Should be fixed on master, can you verify?

**Comment by jayeshkumarbhoi** [comment]
@mroethke Thanks, It is working now. Thanks for quick fix.
